Sistema JYR/Models/CategoriasProducto.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_JYR.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class CategoriasProducto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CategoriasProducto()
        {
            this.Productos = new HashSet<Productos>();
        }
    
        public int Id { get; set; }

        [DisplayName("Categoría")]
        public string Descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Productos> Productos { get; set; }
    }
}

Sistema JYR/Controllers/CategoriasProductoController.cs
 using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Sistema_JYR.Models;

namespace Sistema_JYR.Controllers
{
    public class CategoriasProductoController : Controller
    {
        private SistemaJYREntities db = new SistemaJYREntities();

        // GET: CategoriasProducto
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            return View(db.CategoriasProducto.ToList());
        }

        // GET: CategoriasProducto/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: CategoriasProducto/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Descripcion")] CategoriasProducto categoriasProducto)
        {
            if (ModelState.IsValid)
            {
                db.CategoriasProducto.Add(categoriasProducto);
                db.SaveChanges();
                Session["Categoria"] = "¡La Categoria ha sido creada con éxito!";
                return RedirectToAction("Index");
            }

            return View(categoriasProducto);
        }

        // GET: CategoriasProducto/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CategoriasProducto categoriasProducto = db.CategoriasProducto.Find(id);
            if (categoriasProducto == null)
            {
                return HttpNotFound();
            }
            return View(categoriasProducto);
        }

        // POST: CategoriasProducto/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Descripcion")] CategoriasProducto categoriasProducto)
        {
            if (ModelState.IsValid)
            {
                db.Entry(categoriasProducto).State = EntityState.Modified;
                db.SaveChanges();
                Session["Categoria"] = "La Categoria ha sido actualizada correctamente!";
                return RedirectToAction("Index");
            }
            return View(categoriasProducto);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult filtrarCategoriasAjax(string terminoBusqueda)
        {
            if (terminoBusqueda != null)
            {
                var lista = db.CategoriasProducto.Where(x => x.Descripcion.Contains(terminoBusqueda)
               );
                return PartialView("_ListaCategorias", lista.ToList());
            }
            return View();
        }
    }
}

Sistema JYR/Views/CategoriasProducto/Create.cshtml
@model Sistema_JYR.Models.CategoriasProducto

@{
    ViewBag.Title = "Crear Categoría";
}

<div class="container-fluid">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"> @Html.ActionLink("Inicio", "Index", "Home") </li>
        <li class="breadcrumb-item active"> @Html.ActionLink("Mantenimientos", "Mantenimientos", "Home")</li>
        <li class="breadcrumb-item active"> @Html.ActionLink("Inventario", "Mantenimientos", "Home")</li>
        <li class="breadcrumb-item">@Html.ActionLink("Mantenimiento Categorías de Producto", "Index", "CategoriasProducto")</li>
        <li class="breadcrumb-item active">Crear Categoría</li>
    </ol>
</div>
<div class="container">
    <div class="row">
        <div class="col col-md-6">
            <h2>Crear nueva categoría</h2>
        </div>
        <div class="col col-md-6">
            <a class="btn btn-outline-dark btn-block" href="@Url.Action("Index")">
                <i class="fa fa-arrow-left"></i> Volver
            </a>
        </div>
    </div>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.Label("Nombre de la Categoría", htmlAttributes: new { @class = "control-label col-md-12" })
                <div class="col-md-12">
                    @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-12">
                    <button type="submit" value="Crear" class="btn btn-success btn-block">
                        <i class="fa fa-save"></i> Crear
                    </button>
                </div>
            </div>
        </div>
    }
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Sistema JYR/Views/CategoriasProducto/Edit.cshtml
@model Sistema_JYR.Models.CategoriasProducto

@{
    ViewBag.Title = "Editar Categoría";
}

<div class="container-fluid">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"> @Html.ActionLink("Inicio", "Index", "Home") </li>
        <li class="breadcrumb-item active"> @Html.ActionLink("Mantenimientos", "Mantenimientos", "Home")</li>
        <li class="breadcrumb-item active"> @Html.ActionLink("Inventario", "Mantenimientos", "Home")</li>
        <li class="breadcrumb-item">@Html.ActionLink("Mantenimiento Categorías de Producto", "Index", "CategoriasProducto")</li>
        <li class="breadcrumb-item active">Editar Categoría</li>
    </ol>
</div>


<div class="container">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <div class="row">
                <div class="col col-md-6">
                    <h2>Editar Categoría</h2>
                </div>
                <div class="col col-md-6">
                    <a class="btn btn-outline-dark btn-block" href="@Url.Action("Index")">
                        <i class="fa fa-arrow-left"></i> Volver
                    </a>
                </div>
            </div>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

            <div class="form-group">
                @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-12" })
                <div class="col-md-12">
                    @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-12">
                    <button type="submit" value="Crear" class="btn btn-success btn-block">
                        <i class="fa fa-save"></i> Guardar
                    </button>
                </div>
            </div>
        </div>
    }
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Sistema JYR/Views/CategoriasProducto/Index.cshtml
@model IEnumerable<Sistema_JYR.Models.CategoriasProducto>
@using Sistema_JYR.Models;

@{
    ViewBag.Title = "Mantenimiento Categorías de Productos";
    List<Productos> products = new List<Productos>();
    SistemaJYREntities db = new SistemaJYREntities();
}

    <div class="container-fluid">
        <ol class="breadcrumb container-fluid">
            <li class="breadcrumb-item"> @Html.ActionLink("Inicio", "Index", "Home") </li>
            <li class="breadcrumb-item active"> @Html.ActionLink("Mantenimientos", "Mantenimientos", "Home")</li>
            <li class="breadcrumb-item active"> @Html.ActionLink("Inventario", "Mantenimientos", "Home")</li>
            <li class="breadcrumb-item active">Mantenimiento Categorías de Producto</li>
        </ol>
    </div>

@using (Ajax.BeginForm("filtrarCategoriasAjax", "CategoriasProducto", new AjaxOptions
{
    HttpMethod = "GET",
    UpdateTargetId = "divCategorias",
    InsertionMode = InsertionMode.Replace

}))
{

    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-8">
                <h2><i class="fa fa-list-ul" style="margin-right: 2px"></i>Mantenimiento Categorías</h2>
            </div>
            <div class="col-lg-4">
                <a class="btn btn-dark btn-block" href="@Url.Action("Create")">
                    <i class="fa fa-plus"></i>  Crear Nueva
                </a>
            </div>
        </div>
        <div class="row" style="margin: 2%">
            <div class="col-md-1">
                Filtro:
            </div>
            <div class="col-md-9">
                @Html.TextBox("terminoBusqueda", "", new { @class = "form-control", @placeholder = "Criterio de búsqueda" })
            </div>
            <div class="col-md-1">
                <button type="submit" value="Buscar" class="btn btn-dark btn-block"><i class="fa fa-search"></i></button>
            </div>
            <div class="col-md-1">
                <a class="btn btn-danger btn-block" href="@Url.Action("Index")">
                    <i class="fa fa-trash-o"></i>
                </a>
            </div>
        </div>
    </div>
    
    }
<hr/>
<div class="container-fluid" style="text-align: center" id="divCategorias">
    <table class="table table-striped table-hover table-bordered table-responsive-lg">
        <tr class="thead-light">
            <th>
                Nombre
            </th>
            <th>
                Número de ítems
            </th>
            <th>
                Acciones
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Descripcion)
                </td>
                <td>
                    @{products = db.Productos.Where(x => x.IdCategoria == item.Id).ToList();}
                    @products.Count
                </td>
                <td>
                    <a class="btn btn-dark" href="@Url.Action("Edit", new { id = item.Id })">
                        <i class="fa fa-pencil-square-o"></i>  Editar
                    </a>
                </td>
            </tr>
        }

    </table>
</div>

@if (Session["Categoria"] != null)
{
    switch (Session["Categoria"])
    {
        case "¡La Categoria ha sido creada con éxito!":
            <script type="text/javascript">
                function CreacionCategoria() {
                    Swal.fire({
                        title: '¡La categoría ha sido creada con éxito!',
                        icon: 'success',
                        toast: false,
                        timer: 4000,
                        timerProgressBar: true
                    });
                };
                CreacionCategoria();
            </script>
            Session["Categoria"] = null;
            break;
        case "La Categoria ha sido actualizada correctamente!":
            <script type="text/javascript">
                function EdicionCategoria() {
                    Swal.fire({
                        title: '¡La categoría ha sido actualizada correctamente!',
                        icon: 'success',
                        toast: false,
                        timer: 4000,
                        timerProgressBar: true
                    });
                };
                EdicionCategoria();
            </script>
            Session["Categoria"] = null;
            break;
        default:
            break;
    }
}

Sistema JYR/Views/CategoriasProducto/_ListaCategorias.cshtml
@model IEnumerable<Sistema_JYR.Models.CategoriasProducto>
@using Sistema_JYR.Models;
@{
    List<Productos> products = new List<Productos>();
    SistemaJYREntities db = new SistemaJYREntities();
}

    <div class="container-fluid" style="text-align: center" id="divCategorias">
        <table class="table table-striped table-hover table-bordered table-responsive-lg">
            <tr class="thead-light">
                <th>
                    Nombre
                </th>
                <th>
                    Número de ítems
                </th>
                <th>
                    Acciones
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Descripcion)
                    </td>
                    <td>
                        @{products = db.Productos.Where(x => x.IdCategoria == item.Id).ToList();}
                        @products.Count
                    </td>
                    <td>
                        <a class="btn btn-dark" href="@Url.Action("Edit", new { id = item.Id })">
                            <i class="fa fa-pencil-square-o"></i>  Editar
                        </a>
                    </td>
                </tr>
            } @if (Model.Count() == 0)
            {
                <tr>
                    <td colspan="9">
                        No hay elementos
                    </td>
                </tr>
            }

        </table>
    </div>